Repository ceregousa/slate, pull requests merged in 2020-11, with the labels that each got.

#16 Document member ID for course enrollment
  source/includes/courses/_users.md
Labels: High Priority, LGTM

#17 Document filter[in_library] param for courses endpoint
  source/includes/_courses.md
Labels: LGTM

#18 CP-2629 - Documentation for user tags
  source/includes/_user_tags.md
  source/index.html.md
Labels: LGTM

#19 CP-2679 - Replace previous User Tag documentation with single bulk API
  source/includes/_user_tags.md
Labels: LGTM, Needs Review
